### ISSUE TITLE
Use of crm:P2_has_type in Materials model

### ISSUE THREAD

**Issue by rjyounes** [LD4P/ArtFrame-RareMat#11]
@melanieWacker @sfolsom Do crm:P2_has_type and skos:broader have the same function or at least overlapping functions? They both link a term to a broader term in a hierarchy of terms. If this is true, why have we adopted the crm term rather than the skos one in the Material recommendation, since elsewhere we use the skos terms?  If not, please correct me and explain the difference in usage. Thanks.

**Comment by melanieWacker** [comment]
@rjyounes I think it would be more similar to skos:narrower. Something is made of a material and that material is wood.

**Comment by rjyounes** [comment]
@melanieWacker I thought the model was, for example:

:resource :hasMaterial :material .
:material <predicate> :cotton .
:cotton <predicate> :cloth .

The specific material the resource is made of is a specific cloth, which is narrower than cloth in general. That suggests <predicate> is skos:broader (or crm:P2_has_type). In general it seems to me that if X is a type of Y (e.g., beagle is a type of dog), then Y is the broader term.

**Comment by rjyounes** [comment]
Withdrawing comment.
