### ISSUE TITLE
Limitation Statement recommendation: use bf:Note subtype instead of predicate?

### ISSUE THREAD

**Issue by rjyounes** [LD4P/ArtFrame-RareMat#25]
Did the group consider using a subclass of bf:Note, LimitationNote, instead of a distinct predicate?

**Comment by sfolsom** [comment]
I think we started out with a much more complicated model and kept trimming it down. If it's just going to be a string value "noting" information about limitations... I'd agree a LimitationNote makes sense.

**Comment by melanieWacker** [comment]
In that case -- would it be another option to use the bf:note noteType model rather than subclassing? Especially if it is just a string value.

**Comment by sfolsom** [comment]
Personally, I'd still want to advocate for subclassing of bf:Note. noteType seems so brittle.

**Comment by melanieWacker** [comment]
How about the model proposed by Ray here: https://www.loc.gov/bibframe/docs/pdf/bf2-notes-june2016.pdf
See noteType expressed by external class section.

**Comment by sfolsom** [comment]
Right. The external class could be defined as a subclass of bf:Note.

**Comment by melanieWacker** [comment]
+1 -- looking to do that for some art specific notes.

**Comment by rjyounes** [comment]
So is there a decision to remove the hasLimitationStatement predicate and define instead a LimitationNote subtype?

**Comment by rjyounes** [comment]
Done
