### ISSUE TITLE
Suggestions for definitions in measurement.owl

### ISSUE THREAD

**Issue by rjyounes** [LD4P/ArtFrame-RareMat#8]
Definition of Measurement: would it be clearer to say "dimension" instead of "aspect"? I think I originally suggested "aspect" because "dimension" didn't seem to cover all cases (e.g., file size) but now I think it sounds awkward.

Definition of hasMeasurement: since the domain is unspecified, the definition should not refer to MeasurementGroup. It could be a MeasurementGroup, a Font, etc.

Definition of isMeasurementOf: same as above

Definition of isUnitOf: should be turned around - relationship between unit and measurement

**Comment by melanieWacker** [comment]
Re: hasMeasurement: Should we just say: The relationship of a resource to a measurement?

**Comment by rjyounes** [comment]
Yes, that sounds good.

**Comment by melanieWacker** [comment]
I am just noticing that isMeasurementOf actually has a range of MeasurementGroup. So shouldn't we make it the domain of hasMeasurement? Or leave the range open?

**Comment by rjyounes** [comment]
yes, you're right.

**Comment by melanieWacker** [comment]
The first option or the 2nd?

**Comment by rjyounes** [comment]
Sorry - I wasn't clear. We wanted to leave the range of isMeasurementOf and domain of hasMeasurement open so that they could be used in other contexts, such as a Font having a Measurement without requiring a MeasurementGroup.

**Comment by melanieWacker** [comment]
Ok. Done.
